### ISSUE TITLE
Spigot 1.8.7 Crashing

### ISSUE THREAD

**Issue by lozzthedevppg** [DenizenScript/Denizen-For-Bukkit#1241]
Hi

After installing either the latest successful build or latest release builds of Denizen, It seems that most commands are causing my Spigot 1.8.7 server to crash with the following type of error:-

[20:01:00 INFO]: LozzTheDevPPG issued server command: /npc select
[20:01:00 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:20) [spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException
        at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.fullCheck(AtomicIntegerFieldUpdater.java:433) ~[?:1.8.0_66]
        at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.getAndAdd(AtomicIntegerFieldUpdater.java:477) ~[?:1.8.0_66]
        at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.addAndGet(AtomicIntegerFieldUpdater.java:490) ~[?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1016) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) ~[spigot-1.8.7.jar:git-Spigot-6d16e64-b105298]
        ... 5 more

Can you look into this please 
Thx
-LozzTheDevPPG

**Comment by Morphan1** [comment]
Why are you using 1.8.7? Upgrade your server before posting an issue for latest builds (the ones built for the latest server builds)

**Comment by mcmonkey4eva** [comment]
@lozzthedevppg please do confirm this is fixed on latest 1.8.8.

**Comment by lozzthedevppg** [comment]
ok, I'll upgrade a test server to 1.8.8. and re-try Denizen with latest
build of Citizens there and let you know

**Comment by lozzthedevppg** [comment]
Upgrading to 1.8.8 and still getting the same errors:-

[14:28:34 INFO]: LozzTheDevPPG issued server command: /npc select
[14:28:34 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
~[?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException
        at
java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.fullCheck(AtomicIntegerFieldUpdater.java:433)
~[?:1.8.0_66]
        at
java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.getAndAdd(AtomicIntegerFieldUpdater.java:477)
~[?:1.8.0_66]
        at
java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.addAndGet(AtomicIntegerFieldUpdater.java:490)
~[?:1.8.0_66]
        at
net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1043)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
~[?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        ... 5 more


Any more suggestions?

**Comment by Talamar1** [comment]
What version of Citizens are you using, /npc commands shouldn't error in Denizen. @fullwall ?

**Comment by lozzthedevppg** [comment]
Citizens-2.0.16-beta1 - latest stable build obtained yesterday.

**Comment by mcmonkey4eva** [comment]
Please update Citizens to latest dev release here: http://wiki.citizensnpcs.co/Versions

**Comment by lozzthedevppg** [comment]
I've updated to Citizens to latest build, build 1275 and latest build of
Denizen, build 1602 and I'm still experiencing these peculiar errors:-

[13:22:47 INFO]: LozzTheDevPPG issued server command: /npc select
[13:22:47 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
~[?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException
        at
java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.fullCheck(AtomicIntegerFieldUpdater.java:433)
~[?:1.8.0_66]
        at
java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.getAndAdd(AtomicIntegerFieldUpdater.java:477)
~[?:1.8.0_66]
        at
java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.addAndGet(AtomicIntegerFieldUpdater.java:490)
~[?:1.8.0_66]
        at
net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1043)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
~[?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
~[?:1.8.0_66]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
~[spigot-1.8.8.jar:git-Spigot-5f38d38-18fbb24]
        ... 5 more

Again I've removed the DENIZEN plugin and these errors go away, so its
definitely originating from that plugin. Can you guys actually fix the
error, rather than guess and have me chasing my tail trying different build
versions....!

Thanks
-Lozz

**Comment by Talamar1** [comment]
We can't fix the error until we can determine where the error is being caused.  That java dump shows no plugin code, it is all core server and java engine messages (though it isn't reporting the whole string since it is saying "... 5 more", so the actual error might be in there.  So far, you are the only person that is experiencing this issue so indications would be that it is something in either your server setup or OS configuration.  Until we actually can see an error (other than a class cast conversion), we can't see where it is coming from.

**Comment by mcmonkey4eva** [comment]
@Morphan1 any ideas here?

**Comment by lozzthedevppg** [comment]
Excellent work guys, build 1604 seems to have fixed the errors !

Thank you very much :-)

-LozzTheDevPPG
