### ISSUE TITLE
on player death display null with pvpArena plugin

### ISSUE THREAD

**Issue by Oruss7** [DenizenScript/Denizen-For-Bukkit#1557]
Hello there,

Some strange things occurs with **pvpArena** plugin. if i have **on player death** anywhere in some script, when players dies in arena (made by pvpArena), denizen display **null** on the chat.

So, if i change my **on player death** and add **determine cancelled**, denizen display **cancelled** instead of **null**.

Any ideas ?

**Comment by Oruss7** [comment]
https://github.com/slipcor/pvparena/issues/282#issuecomment-284257135
if that's can help

**Comment by mcmonkey4eva** [comment]
If Denizen is displaying "null", it's because you did "- determine null" or similar.

**Comment by mcmonkey4eva** [comment]
Alternately, it could be something on your server misinterpretted a proper cancellation. and then the "cancelled" appears because you cancelled it twice or something...

**Comment by mcmonkey4eva** [comment]
... Actually, there was a flaw with `determine cancelled` -> I fixed that in the currently processing dev build.

**Comment by Oruss7** [comment]
thank you

**Comment by Oruss7** [comment]
I use last dev build http://ci.citizensnpcs.co/job/Denizen_Developmental/ and bug still here :(
PvpArena cancel this event. May be it's the problem ?

**Comment by Oruss7** [comment]
if pvparena cancel it, denizen cancel it too?

**Comment by mcmonkey4eva** [comment]
w...w hat?

**Comment by Oruss7** [comment]
Player is killed. pvparena cancel the event, and set score etc. Denizen display null. Why ?

**Comment by mcmonkey4eva** [comment]
In what way is it the fault of Denizen? Where is DENIZEN IN PARTICULAR doing that?
