### ISSUE TITLE
on player drags event

### ISSUE THREAD

**Issue by wolfwork** [DenizenScript/Denizen-For-Bukkit#1672]
on player drags in inventory
works fine
on player clicks  in custominv
works fine

on player drags in custominv
dosent work

**Comment by mcmonkey4eva** [comment]
Try build 260+ off http://ci.citizensnpcs.co/job/Denizen_Developmental/
I pushed a relevant fix which is in that build.

**Comment by GershonR** [comment]
Using build 263, but not fixed. There is undefined behavior and it only cancels around 5-10% of the time, if I call cancels drags in a custom inventory it will let you drag and only sometimes cancels.
