### ISSUE TITLE
Invisible Command Broken for Player NPCs

### ISSUE THREAD

**Issue by Elxafil** [DenizenScript/Denizen-For-Bukkit#1819]
So other much testing using all values `true`, `false` and even `toggle` I've figured out the invisible command must be broken, in the latest development of my pets script I've been experimenting with armor_stand and player entities trying to find the right one for my pets to be used for which entails attaching them to the head of the NPC however the problem I have is that with armor_stand NPCs it works without a problem except for the occasional glitch where the armor_stand's NPC name turns into Armorstand instead of the name given but the problem with player NPCs they are not being made invisible at all which is why I reporting this bug. The debug acts as if it completed successfully even when it doesn't: http://prntscr.com/l1x5b6

**Comment by mcmonkey4eva** [comment]
- Are you sure that `n@77` is the correct NPC (making sure due to use of `player.target` tag) and that it is a player-type NPC?
- Can you please post Spigot, Denizen, and Citizens versions? (Use commands: `/version`, then `/version denizen`, then `/version citizens` and screenshot or copypaste the exact output).
- Can you also please post (via pastebin) your Citizens config.yml?
- Do you have any plugins or settings that may interfere with Citizens scoreboard control (used for things like `/npc name` and/or longer than 16 character names), playerlisting alterations (ie the `/npc playerlist` command), or similar?

**Comment by Elxafil** [comment]
@mcmonkey4eva here is the versions: http://prntscr.com/l20tuu

Also here is the config.yml: https://pastebin.com/yuppApJ3

**Comment by Elxafil** [comment]
@mcmonkey4eva tested it with the latest Denizen Developmental, Citizens as of today and the bug is still a problem as seen here: http://prntscr.com/l8g3d7 The debug says it worked but it didn't.

**Comment by mcmonkey4eva** [comment]
You have not responded to the last bulletpoint on my post above.
See also https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by mcmonkey4eva** [comment]
Seems there was a typo in some relevant code, woops!
Fixed in build DEV-436+ from http://ci.citizensnpcs.co/job/Denizen_Developmental/
Thanks for the report!

**Comment by Elxafil** [comment]
Lol I told you I wasn't wrong :P Silly monkey haha

**Comment by Elxafil** [comment]
Hate to be the barer of bad news but it's still happening, downloaded the new Citizens 2 builds and Denizen Developmental builds just a few minutes ago, went to try it and the NPCs are still not turning invisible.

**Comment by mcmonkey4eva** [comment]
It's fixed, see confirmation gif: https://i.imgur.com/fliQzLv.gifv

```
ElxafilToday at 5:53 PM
Whoops I'm on build 433 lol
```
(quote via discord) Always verify version IDs!

**Comment by Elxafil** [comment]
Fixed. My bad...
