### ISSUE TITLE
context.inventory.location is null on player close hopper event 

### ISSUE THREAD

**Issue by killme** [DenizenScript/Denizen-For-Bukkit#940]
According to the docs context.inventory should return an in@, it does.
<in@inventory.location> however returns null.

## Script
```Denizen
    on player closes HOPPER:
            - narrate "CLOSE <context.inventory> <context.inventory.location>"
```
## Expected output:
```
CLOSE in@location[holder=l@52.0,78.0,215.0,world] l@52.0,78.0,215.0,world
```
## Actual output:
```
CLOSE in@location[holder=l@52.0,78.0,215.0,world] null
```
## Debug log
```
+- Executing dCommand: NARRATE/p@player ---------+ 
Filled tag <context.inventory> with 'in@location[holder=l@52.0,78.0,215.0,world]'. 
Filled tag <context.inventory.location> with 'null'. 
ERROR in script 'CAVEOFTWOLOVERS'! Tag <context.inventory.location> is invalid! 
+> Executing 'NARRATE': Narrating='CLOSE  in@location[holder=l@52.0,78.0,215.0,world] null'  Targets='[p@player]' 
```

**Comment by Morphan1** [comment]
What kind of inventory is it?

**Comment by mcmonkey4eva** [comment]
... side comment, thank you for putting all information you thought relevant in a neat and organized manner, you have no idea how rare this is.

**Comment by AnthonyAMC** [comment]
@Morphan1 ```on player closes HOPPER:```

**Comment by Morphan1** [comment]
Oh. Hey, yeah that's nice

**Comment by Morphan1** [comment]
This should be fixed in the latest developmental build

**Comment by killme** [comment]
Updated to ```0.9.6-SNAPSHOT (build 1559)``` ([latest development build at the moment](http://ci.citizensnpcs.co/job/Denizen/lastSuccessfulBuild/)) and it's still the same issue.

**Comment by Morphan1** [comment]
```
http://ci.mineconomy.org/job/Denizen_Developmental/
These are super-duper-developmental.

The main Citizens CI ones are pretty much release builds, we only build every 10+ commits, and only after confirming stability.

(The failed builds were a jenkins error)
```
- mcmonkey4eva

**Comment by killme** [comment]
Thanks, works.
